# nginx proxy address - http://172.17.0.1:53091

name: minio
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  server:
    image: casjaysdevdocker/minio:latest
    container_name: minio-server
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    command: 'server /data --address=":9000" --console-address ":53091"'
    logging: *default-logging
    environment:
      - MINIO_BROWSER_REDIRECT=on
      - TZ=${TZ:-America/New_York}
      - MINIO_REGION_NAME=us-east-1
      - MINIO_BROWSER_SESSION_DURATION=30d
      - MINIO_ROOT_USER=${APP_ADMIN_USER:-administrator}
      - MINIO_ROOT_PASSWORD=${APP_ADMIN_PASS:-nlrKioJFtyb4Oh9MT3oQuL6CFAApTWEg}
      - MINIO_BROWSER_REDIRECT_URL=https://console.${BASE_HOST_NAME}
    ports:
      - '172.17.0.1:53090:9000'
      - '172.17.0.1:53091:53091'
    volumes:
      - './rootfs/data/minio:/data'
    healthcheck:
      test:
        [
          'CMD',
          'curl',
          '-q',
          '-LSsf',
          'http://localhost:53091/minio/health/live',
        ]
      interval: 3s
      retries: 12
    networks:
      - minio

networks:
  minio:
    name: minio
    external: false
