# nginx proxy address - http://172.17.0.1:53091

name: minio
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  app:
    image: minio/minio:latest
    container_name: minio-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    command: 'server /data --address=":9000" --console-address ":9001"'
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      CONTAINER_NAME: minio-app
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
      MINIO_BROWSER: on
      MINIO_REGION: us-east-1
      MINIO_BROWSER_SESSION_DURATION: 30d
      MINIO_ROOT_USER: ${APP_ADMIN_USER:-administrator}
      MINIO_ROOT_PASSWORD: ${APP_ADMIN_PASS:-changeme_admin_password}
      MINIO_BROWSER_REDIRECT_URL: https://console.${BASE_DOMAIN_NAME:-example.com}
    ports:
      - '172.17.0.1:53090:9000'
      - '172.17.0.1:53091:9001'
    volumes:
      - './volumes/data/minio:/data'
    healthcheck:
      test: ['CMD', 'mc', 'ready', 'local']
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - minio
      - proxy
      - cloudflare
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://minio-app:9001'
      - 'cloudflare.hostname=minio.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.minio-app.entrypoints=http'
      - 'traefik.http.routers.minio-app-secure.tls=true'
      - 'traefik.http.routers.minio-app.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.minio-app-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.minio-app.middlewares=minio-app-https-redirect'
      - 'traefik.http.routers.minio-app-secure.entrypoints=https'
      - 'traefik.http.routers.minio-app-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.minio-app-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.minio-app-secure.service=minio-app'
      - 'traefik.http.services.minio-app.loadbalancer.server.port=9001'

networks:
  minio:
    name: minio
    external: false
  proxy:
    external: true
  cloudflare:
    external: true
